name: "Test Workflow"

on:
  workflow_dispatch:

permissions: read-all

jobs:
  safety_check:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Security Check"
        uses: pycord-development/execute-whitelist-action@a837de44d8c7a758d6900c82651c3134f44c574b
        with:
          whitelisted-github-ids: ${{ vars.ALLOWED_USER_IDS }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Test Output"
        run: echo "Hi"
  further_test:
    runs-on: ubuntu-latest
    environment: release
    needs: [safety_check]
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "List Files"
        run: ls
